-- Insert notification types
INSERT INTO notification_types (id, message)VALUES (1, ' updated details in ');
INSERT INTO notification_types (id, message)VALUES (2, ' closed ');
INSERT INTO notification_types (id, message) VALUES (3, ' deleted ');
INSERT INTO notification_types (id, message)VALUES (4, ' left a comment in ');
INSERT INTO notification_types (id, message)VALUES (5, ' mentioned you in ');

-- Insert projects
INSERT INTO projects ("name", code) VALUES ('Ghost', 'GHST');
INSERT INTO projects ("name", code) VALUES ('Cryptid', 'CRPTD');
INSERT INTO projects ("name", code) VALUES ('Shifter', 'SHFTR');
INSERT INTO projects ("name", code) VALUES ('Vampire', 'VMPR');

-- Insert users
INSERT INTO users (full_name, username, settings)
VALUES ('Damien Colt', 'damien.colt', '{"avatarIcon":5,"avatarTint":5,"defaultProject":{"id":1,"name":"Ghost","code":"GHST"},"location":{"latitude":38.5829,"longitude":-121.4747},"maxTravelDistance":5000,"dateFormat":"31 Dec 2000 23:59","defaultSort":"UPDATED","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Sam Walther', 'sam.walther', '{"avatarIcon":1,"avatarTint":0,"defaultProject":{"id":2,"name":"Cryptid","code":"CRPTD"},"location":{"latitude":39.9513,"longitude":-75.1583},"maxTravelDistance":1200,"dateFormat":"31/12/2000 23:59","defaultSort":"RELEVANCE","notifyOnSelfChanges":true,"notifyOnMention":true,"unstarOnIssueClose":true,"starOnIssueCreate":true,"starOnIssueUpdate":true,"starOnIssueAssigned":true,"starOnIssueUpvote":true}');
INSERT INTO users (full_name, username, settings)
VALUES ('Bobby Krieghoff', 'bobby.krieghoff', '{"avatarIcon":4,"avatarTint":2,"defaultProject":{"id":1,"name":"Ghost","code":"GHST"},"location":{"latitude":33.672,"longitude":-117.646},"maxTravelDistance":1650,"dateFormat":"31/12/2000 11:59PM","defaultSort":"UPDATED","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":false,"starOnIssueUpdate":true,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Dean Winchester', 'dean.winchester', '{"avatarIcon":2,"avatarTint":4,"defaultProject":{"id":4,"name":"Vampire","code":"VMPR"},"location":{"latitude":29.7609,"longitude":-95.3664},"maxTravelDistance":3000,"dateFormat":"31 Dec 2000","defaultSort":"RELEVANCE","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":true}');
INSERT INTO users (full_name, username, settings)
VALUES ('Ray Tokarev', 'ray.tokarev', '{"avatarIcon":3,"avatarTint":0,"defaultProject":{"id":1,"name":"Ghost","code":"GHST"},"location":{"latitude":49.2763,"longitude":-123.144},"maxTravelDistance":4350,"dateFormat":"31 Dec 2000","defaultSort":"UPDATED","notifyOnSelfChanges":false,"notifyOnMention":false,"unstarOnIssueClose":false,"starOnIssueCreate":false,"starOnIssueUpdate":false,"starOnIssueAssigned":false,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Dustin Browning', 'dustin.browning', '{"avatarIcon":1,"avatarTint":4,"defaultProject":{"id":1,"name":"Ghost","code":"GHST"},"location":{"latitude":38.9982,"longitude":-104.8613},"maxTravelDistance":920,"dateFormat":"Dec 31 2000 23:59","defaultSort":"RELEVANCE","notifyOnSelfChanges":false,"notifyOnMention":false,"unstarOnIssueClose":false,"starOnIssueCreate":false,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Janine Mauser', 'janine.mauser', '{"avatarIcon":3,"avatarTint":1,"defaultProject":{"id":2,"name":"Cryptid","code":"CRPTD"},"location":{"latitude":36.162,"longitude":-86.7767},"maxTravelDistance":2600,"dateFormat":"12/31/2000 23:59","defaultSort":"UPDATED","notifyOnSelfChanges":true,"notifyOnMention":true,"unstarOnIssueClose":true,"starOnIssueCreate":true,"starOnIssueUpdate":true,"starOnIssueAssigned":true,"starOnIssueUpvote":true}');
INSERT INTO users (full_name, username, settings)
VALUES ('Dana Beretta', 'dana.beretta', '{"avatarIcon":0,"avatarTint":3,"defaultProject":{"id":3,"name":"Shifter","code":"SHFTR"},"location":{"latitude":33.4013,"longitude":-104.5214},"maxTravelDistance":600,"dateFormat":"12/31/2000 11:59PM","defaultSort":"RELEVANCE","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Winston Lebeau', 'winston.lebeau', '{"avatarIcon":1,"avatarTint":1,"defaultProject":{"id":4,"name":"Vampire","code":"VMPR"},"location":{"latitude":32.8813,"longitude":-117.237},"maxTravelDistance":4400,"dateFormat":"Dec 31 2000","defaultSort":"UPDATED","notifyOnSelfChanges":false,"notifyOnMention":false,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":false,"starOnIssueUpvote":true}');
INSERT INTO users (full_name, username, settings)
VALUES ('Vigo Dragunov', 'vigo.dragunov', '{"avatarIcon":3,"avatarTint":3,"defaultProject":{"id":1,"name":"Ghost","code":"GHST"},"location":{"latitude":45.5053,"longitude":-73.5558},"maxTravelDistance":3520,"dateFormat":"31 Dec 2000 23:59","defaultSort":"RELEVANCE","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');
INSERT INTO users (full_name, username, settings)
VALUES ('Lydia Thompson', 'lydia.thompson', '{"avatarIcon":2,"avatarTint":2,"defaultProject":{"id":4,"name":"Vampire","code":"VMPR"},"location":{"latitude":49.3043,"longitude":-123.1437},"maxTravelDistance":1700,"dateFormat":"31/12/2000 23:59","defaultSort":"UPDATED","notifyOnSelfChanges":false,"notifyOnMention":true,"unstarOnIssueClose":false,"starOnIssueCreate":true,"starOnIssueUpdate":false,"starOnIssueAssigned":true,"starOnIssueUpvote":false}');

-- Insert issues
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (4, 'VMPR', 9, NULL, 'Creepy children', 'Witnesses in the French Quarter allege three identical children with ash-colored faces and empty eye sockets begging passerbys at night for "a drink of your heart."Police prescence in the area has increased but no children matching that description has yet been found.', 'MAJOR', 'SUBMITTED', ARRAY[9], ARRAY[]::int[], '2024-11-11T21:32:00', '2024-11-16T23:55:00', 'POINT(29.9551 -90.0589)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 2, NULL, 'Sailor with hook hand - disappears on approach', 'Classic roadside goul; wearing a parka with a sailor''s hat at a jaunty angle. It stands in the middle of the road with the hooked hand raised menacingly. Disappears whenever drivers accelerate to drive around it.', 'NORMAL', 'SUBMITTED', ARRAY[3,4,1,9], ARRAY[1,9], '2024-11-23T05:10:00', '2025-04-27T15:55:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (4, 'VMPR', 10, NULL, 'House stalker', 'Farmsteads reported a tall, bone-thin figure knocking on windows at night. Victims later developed unexplained anemia and all share similar dreams of grand, rotting banquet halls. Security footage shows a tall silhouette though facial features blur unnaturally on playback.', 'MAJOR', 'SUBMITTED', ARRAY[10], ARRAY[4,8,7], '2024-11-26T23:12:00', '2024-12-03T09:51:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 7, NULL, 'Air traffic oddities', 'Civilian air traffic control recorded a sphere moving through Yosemite National Park at hypersonic speeds without any shockwaves. Said to move at an altitude of 50 feet.', 'MINOR', 'SUBMITTED', ARRAY[7,8,2], ARRAY[6,8], '2024-12-06T16:32:00', '2024-12-07T08:19:00', 'POINT(37.8651 -119.5383)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 6, NULL, 'Mining ghouls', 'Commuters near Black Mountain in Kentucky are seeing luminescent and emaciated figures walking by the roads near old mining sites. Sometimes the figures walkk other times just standing. Cannot make out their eyes but based on their bodies it seems they''re always facing the mountain. People have been trying to take pictures but claim their phones/cameras always fail during photography. Elders from nearby communities call them the "ones that never left".', 'NORMAL', 'SUBMITTED', ARRAY[6,8], ARRAY[8], '2024-12-08T10:23:00', '2024-12-13T16:30:00', 'POINT(36.9084 -82.8896)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 5, NULL, 'Finland - highland strangeness', 'Multiple herders reported glimpses of a massive Forest Reindeer with shimmering, water-like hides when walking into moonlight. No tracks left behind in fresh snow and the herders say the reindeer ''speak'' in human voices before vanishing. Field cameras placed along migration routes have so far captured a cold, metallic outline where their image should be.', 'NORMAL', 'SUBMITTED', ARRAY[2,5], ARRAY[1], '2024-12-10T17:56:00', '2024-12-17T13:22:00', 'POINT(64.8789 27.8493)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 4, NULL, 'Concerning shadows in manor house windows', 'Windows at an manor house outside of the abandoned town of Greenwater, California display menacing-looking shadows with an orange-red glow around them. Unclear if this is a hoax by pranksters but highly suspected.', 'NORMAL', 'SUBMITTED', ARRAY[3,4,1,9], ARRAY[1,9], '2024-12-12T14:23:00', '2024-12-12T14:23:00', 'POINT(36.1794 -116.6163)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 4, NULL, 'Convoy of ghost cars with bizarre-looking occupants', 'Late-night drivers overtaken by a convoy of vintage black pick-ups with no license plates. Witnesses claim the drivers'' faces appeared melted, like wax figures in the sun. State troopers found fresh tire tracks — but no vehicles.', 'NORMAL', 'SUBMITTED', ARRAY[4,6,8,9], ARRAY[6,8], '2024-12-12T14:23:00', '2024-12-12T14:23:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 3, NULL, 'Orbs or mutant fireflies troubling community', 'Emit loud buzzing sound as they ''patrol'' the nearby village. Only appear at night and during random days of the month...no pattern detected as yet.', 'NORMAL', 'SUBMITTED', ARRAY[]::int[], ARRAY[]::int[], '2024-12-15T08:11:00', '2024-12-15T08:11:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 1, NULL, 'Woman in white on roadside', 'Seen more than once. Hovers several feet above the curb each time - noiseless and hard to make out a face or clothing because of her bright glow.', 'NORMAL', 'SUBMITTED', ARRAY[2,1], ARRAY[1], '2024-12-16T23:43:00', '2025-03-09T13:39:00', 'POINT(39.0997 -94.5783)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 8, NULL, 'Underwater noises', 'Deep-sea probe captured audio of ''low breathing sound'' at a depth exceeding 10,000 meters. Researchers have already ruled out out known biological or tectonic source. Probe ceased functioning within seven minutes of recording the anomaly.', 'MINOR', 'SUBMITTED', ARRAY[8,5], ARRAY[7,3,2,5], '2024-12-26T19:39:00', '2024-12-27T06:16:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (3, 'SHFTR', 2, 2, 'Suspicious tree breaks in Fraser Valley, plus aggressive hollering and near-miss attacks on hikers', 'Clean mid-height tree breaks in the Harrison Hot Springs area. Large coniferous trees >2 feet in diameter affected. Locals and visiting hikers also reporting ''primal, ape-like shouting'' around Echo Island, and large rocks thrown in their direction when walking near Hicks Lake. People are staying away from the area in the meantime.', 'MINOR', 'SUBMITTED', ARRAY[2,1], ARRAY[1], '2025-01-03T22:54:00', '2025-01-10T08:13:00', 'POINT(49.029 -122.2854)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 4, NULL, 'Multiple fisherman claiming they saw luminous, oblong orbs flying in hexagonal formation at night. Video recordings are available for preliminary review.', '', 'MINOR', 'SUBMITTED', ARRAY[4], ARRAY[]::int[], '2025-01-11T11:38:00', '2025-01-11T11:38:00', 'POINT(31.8361 -119.3062)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 5, NULL, 'Winery investigation', 'Wine workers in California are seeing orbs of different colours move through grapevines. They appear to avoid detection and grapes exposed to their light are said to have higher-than-normal sugar concentrations and abnormal cellular structures.', 'MINOR', 'SUBMITTED', ARRAY[5,1,2], ARRAY[1,2], '2025-01-19T19:01:00', '2025-01-19T19:01:00', 'POINT(38.5596 -122.5355)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (3, 'SHFTR', 9, 1, 'Suspicious ape sightings', 'Big Cypress National Preserve''s reputation for possible Skunk Apes continues with this story - a Canadian couple visiting the park left their camp site in a hurry last week because of an animal invasion into their camp space. The wife claimed it looked like a bear, the husband said it looked like a tall chimp, both shared there was an awful stench in the air minutes before it arrived. They remembered weird vocalizations, like little ''hoop'' noises and teeth clacking when it circled their camp before of rushing it. Only food was stolen, according to the the park ranger that investigated the morning after. They too reported a sulfuric smell and saw newly-broken tree branches about six to seven feet off the ground.', 'NORMAL', 'COMPLETED', ARRAY[9,1,2], ARRAY[]::int[], '2025-01-21T14:01:00', '2025-02-21T17:21:00', 'POINT(25.8588 -81.0338)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 6, NULL, 'Red light in the sky', 'A solitary red light appeared above a remote acacia tree, blinking in a rhythm that Kenyan hikers say looked like Morse code. Light disappeared when they attempted to reach it, and they experienced temporary blindess - vision came back in 30 minutes.', 'NORMAL', 'SUBMITTED', ARRAY[6,9], ARRAY[]::int[], '2025-01-22T14:11:00', '2025-01-22T14:11:00', 'POINT(-1.2666 36.7999)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 7, NULL, 'Banshee of Caplin Cove - more details to come', 'Occuring in Newfoundland - loud sobbing and shrieking heard by fisherman and oceanic researchers by Caplin Cove''s shores. When the sounds start they last for up to a day, and there''s a pattern of fatal attacks occuring after its appearance and wailing (visuals have all the hallmarks of a Wraith''s looks), which has been at least 4-5 times over the last month, according to local residents.', 'NORMAL', 'SUBMITTED', ARRAY[7,1,10], ARRAY[]::int[], '2025-01-23T08:09:00', '2025-01-23T08:09:00', 'POINT(47.1085 -55.7694)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 3, 5, 'Bizarre drownings. Witnesses have seeen ''statuesque looking'' black horses in streams around Loch Carron in Nothern England, these breeds are not endemic to the region. Reports from fisherman include alleged disappearance of several curious onlookers, usually tourists, who approach the animals for selfies.', 'Unable to corroborate these details with missing persons reports for Scotland but needs more research.', 'MAJOR', 'IN_PROGRESS', ARRAY[3,5], ARRAY[3,4,9,11], '2025-01-30T12:34:00', '2025-01-30T12:34:00', 'POINT(57.388 -5.5673)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 11, NULL, 'Frozen river in the summer', 'River froze over during summer night in Romania. Weather over 32C. Fisherman are seeing wispy figures move beneath the ice that vanish upon getting near them.', 'MINOR', 'SUBMITTED', ARRAY[11,1,2], ARRAY[]::int[], '2025-02-03T16:51:00', '2025-02-03T16:51:00', 'POINT(44.4166 26.0999)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 7, NULL, 'Missing forester', 'Logging outfit near Tara National Park is reporting a missing employee. Davor Sokić, a 22 year old Serbian national, meandered from a job site temporarily on his lunch break and hasn''t been seen since. A search party spent the rest of the day looking for him but stopped at night fall. Search resumed the next day and expanded, they looked through a 10 kilometer radius, but neither Sokić or any of his belongings were found until four days later when the small axe he always carried was discovered at the original site of his disappearance, buried almost to the hilt in an old tree stump. The villagers nearby refuse to assist, and have repeated the phrase ''the Forest Master never forgets''. The search party made up of his colleagues are convinced they heard his voice yelling something unintelligible during their search but said it sounded omni-directional and therefore hard to use as a bearing for the search.', 'MAJOR', 'SUBMITTED', ARRAY[7,3,1,11,10], ARRAY[3,1,2,4,6], '2025-02-07T11:11:00', '2025-02-07T11:11:00', 'POINT(43.9404 19.4399)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 10, 10, 'Potential Lycanthropy in Lozère, France', 'Town of Aurillac is in hysterics about wolf-like attacks on humans and livestock over the last 2 months - localized to only 1 night per month, during a full moon. According to my associate researcher already on site the assault on the town and neighboring areas ended shortly before sunrise each time. 2 citizens lost during these weeks, French National Police now involved. 13+ lost livestock, including donkeys, cows, and sheep, all with deep bite marks and gaping wounds from flesh torn apart. No details known about the human passings.', 'MAJOR', 'SUBMITTED', ARRAY[10,8], ARRAY[]::int[], '2025-02-10T03:51:00', '2025-02-10T07:59:00', 'POINT(44.3333 3.6)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (3, 'SHFTR', 1, 1, 'Kentucky residents chased by flying red-eyed creature', 'Creature with big glowing red eyes is flying over Cynthiana, Kentucky on a nightly basis since March. It flies circles around the town and surrounding areas at night, and sometimes more than one pair of eyes is seen in the air. Note that instances of multiple pair of eyes observed is only around the farmlands outside of Cynthiana. Folks are saying it''s Mothman but honestly it''s further west than its normal habitat in Point Pleasant.', 'MINOR', 'COMPLETED', ARRAY[1,2], ARRAY[2], '2025-02-14T02:20:00', '2025-02-16T07:21:00', 'POINT(38.3863 -84.2915)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (3, 'SHFTR', 4, 5, 'Large beast prowling British countryside in Norfolk.', 'Distinct glowing green or red eyes, depending on the eyewitness. Makes a howling sound very different to dogs. Heard it''s twice the size of a rottweiler or german sheperd, for scale. No attacks on humans or animals but stalks fox hunters, bird watchers, hikers etc for several miles while they go through the woods.', 'NORMAL', 'SUBMITTED', ARRAY[4,5], ARRAY[]::int[], '2025-02-14T06:01:00', '2025-02-14T06:05:00', 'POINT(52.6308 1.2973)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 3, 1, 'Entity with disturbing activity', 'Threats occuring to only one family member at a Chicago condo. Entity will aggressively grab their hand and put it on hot surfaces, like a boiling kettle or hot burner on the stove. Victim is reporting always smelling boiled vinegar around the house. Whenever they use the space heater it dials itself to the highest temperature and this only happens to them. The crucifix they wear around their neck has been bending slowly since they moved in last year.', 'NORMAL', 'IN_PROGRESS', ARRAY[3,4,1,7,9,10,2], ARRAY[4,1,7,9,10,2], '2025-02-14T06:01:00', '2025-02-19T09:23:00', 'POINT(41.8818 -87.6231)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 3, 3, 'Muskrat Lake: Possible Wendigo(s)', 'Bizarre attacks on communities in Whitewater Region in Ontario. Attempts of cannibalism by individuals unknown to the area. Algonquin leaders suggest it''s the work of a Wendigo from the surrounding woodlands. Lots of small game was found dead in Westmeath Provincial Park nearby with signs of bites and being only partially eaten, which is unusual for local predators.', 'MAJOR', 'IN_PROGRESS', ARRAY[3,4,9], ARRAY[4,9,5,1], '2025-02-19T10:10:00', '2025-03-01T08:10:00', 'POINT(45.4614 -77.6541)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 9, 9, 'A friendly repairman?', 'A family in Canada is claiming that broken household goods and children''s toys are being "fixed" by a spirit in their home. Apparently any broken item left in their attic overnight is fixed the next morning. The homeowner says this activity began some time ago with her children who were told by "Mr. Kline" that he wants to help around the house. According to their mother Arthur Kline owned the home some 60 years ago, and has been deceased as long.', 'MINOR', 'IN_PROGRESS', ARRAY[9,10], ARRAY[10], '2025-02-20T23:01:00', '2025-02-24T23:21:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 10, 9, 'Underwater skeletons with irregular growths and spectral influence', 'Divers uncovered skeletal remains exhibiting spiral twists along the femurs and ribs, as if the bones had grown while rotating at unnatural speeds. Carbon dating returned conflicting results: some sections registered as 200,000 years old, others 18 hours old. Sample analysis halted after two technicians began speaking a dead language in unison.', 'MAJOR', 'SUBMITTED', ARRAY[10,9], ARRAY[9,11], '2025-02-22T11:35:00', '2025-02-24T10:23:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 8, NULL, 'Global tree-man apparition', 'Witnesses in disparate locations like Whittier, Alaska and Schwerin, Germany have seen a figure covered in gnarled bark that has a grotestquely-wide smile with "shimmering-teeth". Doesn''t attack but makes a thin "creepy" laughing sound. Appearing in woodlands by water.', 'NORMAL', 'SUBMITTED', ARRAY[8], ARRAY[]::int[], '2025-02-23T08:19:00', '2025-02-23T08:19:00', 'POINT(60.7711 -148.6733)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 7, 7, 'House plagued with blue orbs moving through rooms at random times of the day. No known risks to the family.', 'Noise-less glowing spheres are showing up in a home in Lunenburg, Nova Scotia, Canada. They''re usually blue but sometimes can be a light purple color. The residents cannot see inside the ball, say that the glow makes it hard to see through it and also see its physical edges. Apparently it hurts to look at it for longer than a few seconds. They''re baseball-sized and travel in groups of 2 or 3 at a time, several feet off the ground. Their appearance is unpredictable i.e. any hour of the day.', 'MINOR', 'COMPLETED', ARRAY[7], ARRAY[]::int[], '2025-02-26T05:06:00', '2025-02-27T08:16:00', 'POINT(44.3728 -64.318)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 9, NULL, 'Requires specialized geology expert', 'A deep-earth survey team is seeing a man made of stone move through abandoned sections of a gold mine. South African mining surveyors are saying that they have to leave their work because of the seismic activity that follows.', 'MAJOR', 'SUBMITTED', ARRAY[9], ARRAY[]::int[], '2025-02-27T09:29:00', '2025-02-28T07:58:00', 'POINT(-29.046 25.063)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 10, NULL, 'California Dunes', 'Tourists hiking in the dunes reported encountering a tall figure cloaked in whirling dust. When the wind passed, they glimpsed features cobbled together from the faces of people they''d known in life — friends, dead relatives, childhood teachers. One hiker touched the entity and lost all autobiographical memory for 72 hours.', 'NORMAL', 'SUBMITTED', ARRAY[10], ARRAY[]::int[], '2025-02-28T15:33:00', '2025-03-13T13:39:00', 'POINT(36.6485 -117.0824)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 10, NULL, 'Giant walkers', 'Pilot saw "bleached stick-like figures" well over 20 meters tall walking across California desert, unable to take pictures due to plane speed and patchy cloud cover. Subsequent visits only reveal scorched trails where the figures walked.', 'NORMAL', 'SUBMITTED', ARRAY[10], ARRAY[]::int[], '2025-02-28T15:33:00', '2025-02-28T15:33:00', 'POINT(35.425 -116.8919)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 3, NULL, 'Calf experiments, foreign objects found. Unlike recent cattle activity.', 'Five calves in cow herd found dead overnight with surgical incisions in the Sternohyoid muscle. All equal length = 3.5cm. No blood around surrounding tissue or on the ground. Farmer extracted a small, black, "bony foreign object" from each calf and has kept them for investigation.', 'NORMAL', 'SUBMITTED', ARRAY[3,2], ARRAY[]::int[], '2025-02-28T18:31:00', '2024-03-02T10:44:00', 'POINT(35.3297 -115.5495)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (3, 'SHFTR', 4, 4, 'Eerie nautical sightings around Southern Ocean in Antartica. Smooth humanoid creature found swimming alone, last seen near Balleny Islands.', 'Likely a Ningen sighting, it has all the signs; smooth & pale skin, faint to non-existant facial features and at least 5-10 metres long. Incredibly elusive, stays far from research vessels and quickly disappears when approached.', 'NORMAL', 'COMPLETED', ARRAY[4,6,8,9], ARRAY[6,8], '2025-03-01T21:45:00', '2025-03-10T05:00:00', 'POINT(-66.9166 163.3333)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 6, 6, 'Highway stalking in Los Lunas', 'Police officer reported stopping on Highway 25 in New Mexico a few nights ago to inspect an animal he saw curled up on the side of the road. Before he got out of his car he saw the creature resembling a large wolf or coyote in his rear view mirror stand up on its two legs and walk over to his vehicle. The cop said the creature''s eyes shined bright, like 2 strong flash lights, and he immediately accelerated his car, and despite its speed the animal pursued him for several miles and then turned abruptly and ran into the desert and wasn''t seen again.', 'MINOR', 'COMPLETED', ARRAY[6,1], ARRAY[]::int[], '2025-03-12T18:23:00', '2025-03-19T11:12:00', 'POINT(34.8056 -106.7344)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (2, 'CRPTD', 11, 5, 'Faroe Islands Selkie', 'Local named Henrik Hansen describes an encounter with an unidentified female by the shores of Toftir in the Faroe Islands. Said she wore no clothes and acted in a state of confusion. The only other observable was a seal pelt lying near her. She spoke a phrase in what Henrik recognized as old Faroese but couldn''t fully understand. She then disappeared into the surf. Henrik has since returned to the shores daily to see if she''s there and has instead observes a gray seal watching him from water; this has happened every time he goes to the shore.', 'MINOR', 'SUBMITTED', ARRAY[11,5,8], ARRAY[8], '2025-03-12T20:33:00', '2025-03-12T20:35:00', 'POINT(61.8925 -6.9729)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 6, 2, 'Shadowy figure disturbing drivers in Washington state', 'Sounds like a Wraith case; shadowy figure has been seen off and on for years on Black Pine Pass; witnesses report a chill to the bone when they drive by it and faulty car electronics, like the headlights flicker for a few moments on otherwise functional cars. The figure is amorphous but somewhat human shaped, which is why witnesses say it gets their attention. It''s been an urban legend in the area for generations. There have been several car accidents (no fatalities) on the road bend it likes to appear at.', 'MAJOR', 'IN_PROGRESS', ARRAY[6,2,4], ARRAY[4], '2025-03-14T00:43:00', '2025-03-14T00:45:00', 'POINT(48.3132 -120.2764)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 11, NULL, 'Hotel room with repetitive anomalies', 'Local investigators say a single room (#309) in Hotel Mazarin in New Orleans has repeat occurrences across all reservations where every guest in the last month has told the front desk about the same specific anomalies. They''ve all claimed a smell of ''rose water-like perfume'' that fills up the room starting in the morning and takes hours to go away. They''ve also heard sing-song humming, told it sounds "like it''s coming from both inside the room and via the walls to the adjoining unit #311, hard to place". The hotel has confirmed that room 311 has had no occupants in over 10 days as they''re renovating the bathroom.', 'MINOR', 'SUBMITTED', ARRAY[11,9], ARRAY[1,2,3,4,5,6,7,8,9], '2025-03-14T08:30:00', '2025-03-14T08:30:00', 'POINT(29.951 -90.0715)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (4, 'VMPR', 11, NULL, 'Livestock drained of blood', 'Multiple livestock deaths attributed to blood loss. Forensic tests showed small punctures on the animals consistent with multiple micro-siphoning wounds, not typical predator marks. Locals refuse to pass the area at night.', 'MAJOR', 'SUBMITTED', ARRAY[11], ARRAY[10], '2025-03-22T07:52:00', '2025-03-22T07:52:00', NULL, NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 4, NULL, 'Campers are seeing their own reflections walking independently across the desert some distance away.', 'One hiker''s ''copy'' shouted an offer for water from a broken glass jug.', 'NORMAL', 'SUBMITTED', ARRAY[4], ARRAY[]::int[], '2025-04-02T11:19:00', '2025-04-02T11:19:00', 'POINT(34.9189 -119.3105)', NEXTVAL('custom_seq'));
INSERT INTO issues (project_id, project_code, author_id, assignee_id, title, description, priority, "state", watchers, upvotes, created_at, modified_at, "location", "number")
VALUES (1, 'GHST', 1, NULL, 'Woman pacing the cemetery ruins', 'Appears to be on fire. Trailing smoke but leaving no scorch marks. Infrared scans show her body temperature hovering just below freezing.', 'NORMAL', 'SUBMITTED', ARRAY[1,2], ARRAY[]::int[], '2025-04-22T17:55:00', '2025-04-22T17:55:00', 'POINT(36.8301 -120.1182)', NEXTVAL('custom_seq'));

-- Insert comments
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (132, 2, 3, 'I''d like to bump the priority of this one given the livestock deaths, conferring with @dean.winchester first', '2024-03-02T10:44:00', '2024-03-02T10:44:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (100, 4, 9, 'Children with Renfield''s syndrome maybe?', '2024-11-16T23:55:00', '2024-11-16T23:55:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (102, 4, 7, 'Big vampire vibes from this story, guessing that''s pretty obvious. Let me know if you need help.', '2024-12-03T09:51:00', '2024-12-03T09:51:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (103, 1, 8, 'Gut feeling this is a black program aircraft doing testing.', '2024-12-07T08:19:00', '2024-12-07T08:19:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (104, 1, 10, 'Be careful with these, I had a similar job many years ago and it seemed benign on the surface but got hairy FAST', '2024-12-13T16:30:00', '2024-12-13T16:30:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (105, 2, 5, '@ray.tokarev Can you share the pictures? I have some ideas of extracting data from them', '2024-12-17T13:22:00', '2024-12-17T13:22:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (110, 2, 5, 'Would love to see what becomes of this. Hope it''s a crazy find but not too crazy lol.', '2024-12-27T06:16:00', '2024-12-27T06:16:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (111, 3, 2, 'Fraser Valley is a known hotbed for squatch activity, they''re rarely hostile so this could be interesting. Submitting it at Priority = Normal for the time being but paying close attention to what the data collection shows.', '2025-01-03T22:59:00', '2025-01-03T22:59:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (114, 3, 1, 'Beginning investigation with park ranger interview', '2025-01-21T16:15:00', '2025-01-21T16:15:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (114, 3, 1, 'Unable to recreate experience despite camping on site for 48 hours. No smells or noises to suggest Skunk Ape visit in my time there, though I saw the broken brances and large foot tracks (>18 inches) around the site the couple were at', '2025-01-23T15:31:00', '2025-01-23T15:31:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (117, 2, 5, 'Arrived in Scotland, beginning talks with local experts and collecting testimony', '2025-02-01T08:27:00', '2025-02-01T08:27:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (119, 1, 7, 'Probable Leshi, in which case this would be a hard case to follow up on. Possible he''s still alive if actually just disoriented and lost, but case will need to be assigned ASAP.', '2025-02-07T15:31:00', '2025-02-07T15:31:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (120, 2, 10, '@dana.beretta you''ve got zoology expertise, right? Care to join the investigation?', '2025-02-10T07:59:00', '2025-02-10T07:59:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (122, 3, 4, 'Assigning to you @ray.tokarev since this isn''t your first rodeo with Black Shuck and you''re already in the area for other research. Was flipping between low and normal priority for this one, erred on the side of caution despite lack of attacks.', '2025-02-14T06:05:00', '2025-02-15T09:30:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (121, 3, 1, 'I think this is a mistaken identity situation, not Mothman. I think it''s birds with large wing spans i.e. owls or herons. Suggesting this because Mothman has always been a singular sighting - there''s never been a case of two at the same time.', '2025-02-15T07:00:00', '2025-02-15T07:00:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (121, 3, 2, 'I agree with @damien.colt, time of year suggests it could be large migratory birds. Cranes a possibility. Mothman has never left the West Virgina area as far as our records can tell.', '2025-02-16T07:21:00', '2025-02-16T07:21:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (123, 1, 3, 'Asking @damien.colt to take point on this, he''s had a lot of prior success with Poltergeist/malevolent spirits', '2025-02-17T15:01:00', '2025-02-17T15:01:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (123, 1, 7, 'This sounds like something I dealt with a decade ago. DM me', '2025-02-18T08:50:00', '2025-02-18T08:50:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (123, 1, 1, 'Landed in Chicago a few hours ago, about to start collecting video evidence. Had the first conversation with the victim, there''s lots more concerning behavior to deal with.', '2025-02-19T09:23:00', '2025-02-19T09:23:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (126, 1, 3, 'Absolutely dumbfounded by this one, may the most interesting case I''ve seen in months. @winston.lebeau if you need a co-lead I am all yours, would love a crack at this investigation too.', '2025-02-24T10:23:00', '2025-02-24T10:23:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (125, 1, 10, 'Jealous of this one, nice to a case where they''re just helpful!', '2025-02-24T22:51:00', '2025-02-24T22:51:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (125, 1, 9, 'Lol @vigo.dragunov I knew you''d love this. I arrive in Guelph tomorrow to check it out, will tell you about it later', '2025-02-24T23:21:00', '2025-02-24T23:21:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (128, 1, 7, 'Research complete. ', '2025-02-27T08:16:00', '2025-02-27T08:16:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (129, 1, 3, 'I have a rock guy if you need, text me for his digits', '2025-02-28T07:58:00', '2025-02-28T07:58:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (124, 1, 9, 'Been following this for some time, noticed it''s both a Major priority and in progress but no updates? Anything to report @bobby.krieghoff?', '2025-03-01T08:10:00', '2025-03-01T08:10:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (133, 3, 6, 'Adding myself as a watcher because I really want to see what the investigation brings up', '2025-03-01T22:03:00', '2025-03-01T22:03:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (109, 1, 11, 'Location needs to be double-checked...', '2025-03-09T13:39:00', '2025-03-09T13:39:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (101, 1, 11, 'Anyone wants to check if this is still a problem?', '2025-03-09T13:39:00', '2025-04-27T15:55:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (133, 3, 8, 'In the same boat as @dustin.browning, though I think these are beluga sightings', '2025-03-10T05:00:00', '2025-03-10T05:00:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (135, 2, 11, 'Assinging to @ray.tokarev given his relative promixity to the event', '2025-03-12T20:35:00', '2025-03-12T20:35:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (130, 1, 1, 'Recognize this story - this is has been happening there for years, maybe even decades. Just FYI.', '2025-03-13T13:39:00', '2025-03-13T13:39:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (136, 1, 6, 'Assigning to @sam.walther since he grew up not far away from the area, probably knows the legend already.', '2025-03-14T00:45:00', '2025-03-14T00:45:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (134, 2, 6, 'Completed investigation after a week of interviews and data collection. Given the rarity of this event and no prior attacks from Skinwalkers in this area this case is deemed closed until further notice.', '2025-03-19T08:02:00', '2025-03-19T08:02:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (138, 4, 10, 'Time to play a game - vampire, alien, or cryptid?', '2025-03-27T08:55:00', '2025-03-27T08:55:00');
INSERT INTO "comments" (issue_number, project_id, author_id, "content", created_at, modified_at)
VALUES (140, 1, 3, 'Very familiar story, I think a similar ghost was in my second week on the job.', '2025-04-23T06:45:00', '2025-04-23T06:45:00');

-- Insert notifications
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 4, 3, 132, 2, '2024-03-02T10:44:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 8, 10, 120, 2, '2025-02-10T07:59:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 5, 4, 122, 3, '2025-02-14T06:05:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 1, 2, 121, 3, '2025-02-16T07:21:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 1, 3, 123, 1, '2025-02-17T15:01:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (1, 1, 9, 114, 3, '2025-02-21T17:21:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 9, 3, 126, 1, '2025-02-24T10:23:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 10, 9, 125, 1, '2025-02-24T23:21:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 3, 4, 124, 1, '2025-03-01T08:10:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (4, 1, 11, 109, 1, '2025-03-09T13:39:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 6, 8, 133, 3, '2025-03-10T05:00:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 5, 11, 135, 2, '2025-03-10T05:00:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (5, 2, 6, 136, 1, '2025-03-14T00:45:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (2, 1, 6, 134, 2, '2025-03-19T11:12:00');
INSERT INTO notifications (notification_type_id, receiver_id, sender_id, issue_number, project_id, created_at)
VALUES (4, 1, 9, 101, 1, '2025-04-27T15:55:00');